name: Security

on:
  push:
    branches:
      - master
  pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4.2.2

            - uses: actions/setup-node@v4.1.0

            - run: npm audit
